import "../pug/layouts/main-header/main-header-nav";
import "../pug/components/_ui/sliders/main-slider/main-slider";
import "../pug/components/_ui/sliders/infinity-slider/infinity-slider";
import "../pug/components/_ui/yMaps/yMaps";
import "../pug/components/_ui/accordeon/accordeon";
import "../pug/components/_ui/nav/top-multilevel-menu/top-multilevel-menu";
import "./modules/fancy";
import "./modules/modal";
import "./modules/table-wrapper";
